version: 0.2

env:
  secrets-manager:
    ENVIRONMENT_FILE: inokimdashboard-$ENVIRONMENT-bgate-environment

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Deploying projects
      - echo "$ENVIRONMENT_FILE" > .env
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 355431993068.dkr.ecr.eu-central-1.amazonaws.com
      - docker-compose -f docker-compose-$ENVIRONMENT-app.yml build
      - docker push 355431993068.dkr.ecr.eu-central-1.amazonaws.com/inokimdashboard-$ENVIRONMENT/bgate:latest
      - aws ecs update-service --force-new-deployment --service inokimdashboard-$ENVIRONMENT-bgate-service --cluster inokimdashboard-$ENVIRONMENT-main-cluster
  post_build:
    commands:
      - echo Deploy complete
